In [1]:
import numpy as np

In [2]:
an_array = np.array([3, 33, 333])
print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [9]:
another = np.array([[11,12,13],[21,22,23]])
print(another)
print(another.shape)
print(another[1][1], another[1][2])

[[11 12 13]
 [21 22 23]]
(2, 3)
22 23


In [10]:
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [12]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [13]:
a_slice[0][0] = 92
print(a_slice)
print(an_array)

[[92 13]
 [22 23]]
[[11 92 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [15]:
a_slice2 = np.array(an_array[:2, 1:3])
print(a_slice2)

[[92 13]
 [22 23]]


In [16]:
a_slice2[0][0] = 82
print(a_slice2)
print(a_slice)
print(an_array)

[[82 13]
 [22 23]]
[[92 13]
 [22 23]]
[[11 92 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [17]:
print(an_array)

[[11 92 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [21]:
r_ind = np.array([0,1,2])
c_ind = np.array([0,1,2])
print(an_array[0,0],an_array[r_ind,c_ind])

11 [11 22 33]


In [22]:
print(an_array)

[[11 92 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [23]:
a1 = an_array[an_array>30]

In [24]:
print(a1)

[92 31 32 33 34]


In [26]:
arr = 10 * np.random.randn(2,5)
print(arr)

[[ -0.52943552   3.64344138   0.80877462  -1.26564977  -5.13686092]
 [-11.17698363   9.59544983   4.69895463  -1.38109284 -12.01473436]]


In [30]:
print(arr.mean())
print(arr.mean(axis=1))
print(arr.mean(axis=0))
print(arr.sum())

-1.2758136573853065
[-0.49594604 -2.05568127]
[-5.85320958  6.61944561  2.75386463 -1.3233713  -8.57579764]
-12.758136573853065


In [31]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
add_rows = np.array([1,0,2])
print(add_rows)

[1 0 2]


In [34]:
y = start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [37]:
a = np.array([[0,0],[0,0]])
b1 = np.array([1,1])
b2 = 1
print(a)
print(b1)
print(b2)

[[0 0]
 [0 0]]
[1 1]
1


In [38]:
print(a+b1)

[[1 1]
 [1 1]]


In [39]:
print(a+b2)

[[1 1]
 [1 1]]


In [46]:
t1 = np.arange(15).reshape(3,5)
print(t1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [48]:
t2 = t1.reshape(5,3)
print(t2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [52]:
from skimage import data
import imageio
photo_data = imageio.imread('./wifire/sd-3layers.jpg')
type(photo_data)

imageio.core.util.Image